### PR TITLE
Whitelist patch

### PR DESCRIPTION
**Pull request by mdavis332**
Suggestion for adding whitelist of domains not to check if they come up in the stream. There's probably a more elegant solution to this, but this seemed to work.

### CODE REVIEW

**Review by OsintUK — APPROVED** [review]

**Review by OsintUK — COMMENTED** [review]
I'm getting a Exception has occurred: KeyError
'whitelist'

Any thoughts on why this could be? thanks

**Comment by mdavis332** [comment]
> I'm getting a Exception has occurred: KeyError 'whitelist'
> 
> Any thoughts on why this could be? thanks

It's been a few days since I contributed this PR so my recollection may not be the freshest :) Do you have a full error including line number for the `KeyError`? I wonder if the `whitelist` section isn't defined in your `suspicious.yml` or `external.yml` files...

**Comment by OsintUK** [comment]
Exception has occurred: KeyError
'whitelist' 
File "/Users/1/phishing_catcher/catch_phishing.py", line 160, in <module>
    if external['whitelist'] is not None:

**Comment by OsintUK** [comment]
I've also added your four commits

**Comment by OsintUK** [comment]
Sorry @mdavis332 it seems it was an indentation issue on the suspicious.yml haha

**Pull request closed without merging**
